disable older postgres driver tests
github actions uses PG 14 which doesn't support the older connection methods

throws

lucee.runtime.exp.NativeException: org.postgresql.util.PSQLException: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.